[package]
name = "custom_auth"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
axum-extra = { version = "0.10.1", features = ["cookie"] }
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.9"
tokio = { version = "1.45.0", features = ["full"] }
jsonwebtoken = "9"
